SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`TB_PROFESSOR`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_PROFESSOR` (
  `MATRICULA` INT NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(45) NOT NULL ,
  `TELEFONE` VARCHAR(15) NOT NULL ,
  `EMAIL` VARCHAR(60) NULL ,
  `AREA` VARCHAR(20) NULL ,
  `LOGIN` VARCHAR(10) NOT NULL ,
  `SENHA` VARCHAR(10) NOT NULL ,
  `CORDENADOR` CHAR(1) NOT NULL ,
  PRIMARY KEY (`MATRICULA`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_DISCIPLINA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_DISCIPLINA` (
  `COD_DISCIPLINA` INT NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(40) NOT NULL ,
  `CARGA_HORARIA` INT NOT NULL ,
  `PERIODO_DISCIPLINA` CHAR(2) NOT NULL ,
  `TIPO_DISCIPLINA` CHAR(1) NOT NULL ,
  PRIMARY KEY (`COD_DISCIPLINA`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_HORARIOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_HORARIOS` (
  `ID_HORARIOS` INT NOT NULL AUTO_INCREMENT ,
  `DIA_SEMANA` VARCHAR(10) NOT NULL ,
  `HORARIO_INICIAL` VARCHAR(5) NULL ,
  `HORARIO_FINAL` VARCHAR(5) NULL ,
  PRIMARY KEY (`ID_HORARIOS`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_SEMESTRE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_SEMESTRE` (
  `ID_SEMESTRE` INT NOT NULL AUTO_INCREMENT ,
  `ANO` SMALLINT NOT NULL ,
  `PERIODO` CHAR(2) NOT NULL ,
  PRIMARY KEY (`ID_SEMESTRE`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_TURMA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_TURMA` (
  `ID_TURMA` INT NOT NULL AUTO_INCREMENT ,
  `QUANTIDADE_ALUNO` SMALLINT NOT NULL ,
  `TOTAL_APROVADOS` SMALLINT NOT NULL ,
  `TOTAL_REPROVADOS_FALTA` SMALLINT NOT NULL ,
  `TOTAL_REPROVADOS_MEDIA` SMALLINT NOT NULL ,
  `ID_SEMESTRE` INT NULL ,
  `MATRICULA_PROFESSOR` INT NULL ,
  `COD_DISCIPLINA` INT NULL ,
  PRIMARY KEY (`ID_TURMA`) ,
  INDEX `fk_TB_TURMA_TB_SEMESTRE` (`ID_SEMESTRE` ASC) ,
  INDEX `fk_TB_TURMA_TB_PROFESSOR` (`MATRICULA_PROFESSOR` ASC) ,
  INDEX `fk_TB_TURMA_TB_DISCIPLINA` (`COD_DISCIPLINA` ASC) ,
  CONSTRAINT `fk_TB_TURMA_TB_SEMESTRE`
    FOREIGN KEY (`ID_SEMESTRE` )
    REFERENCES `mydb`.`TB_SEMESTRE` (`ID_SEMESTRE` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_TURMA_TB_PROFESSOR`
    FOREIGN KEY (`MATRICULA_PROFESSOR` )
    REFERENCES `mydb`.`TB_PROFESSOR` (`MATRICULA` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_TURMA_TB_DISCIPLINA`
    FOREIGN KEY (`COD_DISCIPLINA` )
    REFERENCES `mydb`.`TB_DISCIPLINA` (`COD_DISCIPLINA` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_TURMA_HORARIOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_TURMA_HORARIOS` (
  `ID_TURMA` INT NOT NULL ,
  `ID_HORARIOS` INT NOT NULL ,
  PRIMARY KEY (`ID_TURMA`, `ID_HORARIOS`) ,
  INDEX `fk_TB_TURMA_has_TB_HORARIOS_TB_TURMA` (`ID_TURMA` ASC) ,
  INDEX `fk_TB_TURMA_has_TB_HORARIOS_TB_HORARIOS` (`ID_HORARIOS` ASC) ,
  CONSTRAINT `fk_TB_TURMA_has_TB_HORARIOS_TB_TURMA`
    FOREIGN KEY (`ID_TURMA` )
    REFERENCES `mydb`.`TB_TURMA` (`ID_TURMA` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_TURMA_has_TB_HORARIOS_TB_HORARIOS`
    FOREIGN KEY (`ID_HORARIOS` )
    REFERENCES `mydb`.`TB_HORARIOS` (`ID_HORARIOS` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`TB_HORARIOS_PROFESSOR`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_HORARIOS_PROFESSOR` (
  `ID_HORARIOS` INT NOT NULL ,
  `MATRICULA` INT NOT NULL ,
  `TIPO_HORARIO` CHAR(1) NOT NULL ,
  `ID_SEMESTRE` INT NULL ,
  PRIMARY KEY (`ID_HORARIOS`, `MATRICULA`) ,
  INDEX `fk_TB_HORARIOS_has_TB_PROFESSOR_TB_HORARIOS` (`ID_HORARIOS` ASC) ,
  INDEX `fk_TB_HORARIOS_has_TB_PROFESSOR_TB_PROFESSOR` (`MATRICULA` ASC) ,
  INDEX `fk_TB_HORARIOS_PROFESSOR_TB_SEMESTRE` (`ID_SEMESTRE` ASC) ,
  CONSTRAINT `fk_TB_HORARIOS_has_TB_PROFESSOR_TB_HORARIOS`
    FOREIGN KEY (`ID_HORARIOS` )
    REFERENCES `mydb`.`TB_HORARIOS` (`ID_HORARIOS` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_HORARIOS_has_TB_PROFESSOR_TB_PROFESSOR`
    FOREIGN KEY (`MATRICULA` )
    REFERENCES `mydb`.`TB_PROFESSOR` (`MATRICULA` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_HORARIOS_PROFESSOR_TB_SEMESTRE`
    FOREIGN KEY (`ID_SEMESTRE` )
    REFERENCES `mydb`.`TB_SEMESTRE` (`ID_SEMESTRE` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`TB_DISCIPLINA_PROFESSOR`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_DISCIPLINA_PROFESSOR` (
  `COD_DISCIPLINA` INT NOT NULL ,
  `MATRICULA` INT NOT NULL ,
  PRIMARY KEY (`COD_DISCIPLINA`, `MATRICULA`) ,
  INDEX `fk_TB_DISCIPLINA_has_TB_PROFESSOR_TB_DISCIPLINA` (`COD_DISCIPLINA` ASC) ,
  INDEX `fk_TB_DISCIPLINA_has_TB_PROFESSOR_TB_PROFESSOR` (`MATRICULA` ASC) ,
  CONSTRAINT `fk_TB_DISCIPLINA_has_TB_PROFESSOR_TB_DISCIPLINA`
    FOREIGN KEY (`COD_DISCIPLINA` )
    REFERENCES `mydb`.`TB_DISCIPLINA` (`COD_DISCIPLINA` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_DISCIPLINA_has_TB_PROFESSOR_TB_PROFESSOR`
    FOREIGN KEY (`MATRICULA` )
    REFERENCES `mydb`.`TB_PROFESSOR` (`MATRICULA` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`TB_PROFESSOR_SEMESTRE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`TB_PROFESSOR_SEMESTRE` (
  `MATRICULA` INT NOT NULL ,
  `ID_SEMESTRE` INT NOT NULL ,
  `VALIDACAO` CHAR(1) NOT NULL ,
  PRIMARY KEY (`MATRICULA`, `ID_SEMESTRE`) ,
  INDEX `fk_TB_PROFESSOR_has_TB_SEMESTRE_TB_PROFESSOR` (`MATRICULA` ASC) ,
  INDEX `fk_TB_PROFESSOR_has_TB_SEMESTRE_TB_SEMESTRE` (`ID_SEMESTRE` ASC) ,
  CONSTRAINT `fk_TB_PROFESSOR_has_TB_SEMESTRE_TB_PROFESSOR`
    FOREIGN KEY (`MATRICULA` )
    REFERENCES `mydb`.`TB_PROFESSOR` (`MATRICULA` )
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TB_PROFESSOR_has_TB_SEMESTRE_TB_SEMESTRE`
    FOREIGN KEY (`ID_SEMESTRE` )
    REFERENCES `mydb`.`TB_SEMESTRE` (`ID_SEMESTRE` )
    ON DELETE RESTRICT
    ON UPDATE CASCADE);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
