//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : Horarios.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.entidade;

import java.sql.Time;


public class Horarios {
	private String dia_semana;
	private Time hora_inicial;
	private Time hora_final;
	
	public String getDia_semana() {
		return dia_semana;
	}
	public void setDia_semana(String dia_semana) {
		this.dia_semana = dia_semana;
	}
	public Time getHora_inicial() {
		return hora_inicial;
	}
	public void setHora_inicial(Time hora_inicial) {
		this.hora_inicial = hora_inicial;
	}
	public Time getHora_final() {
		return hora_final;
	}
	public void setHora_final(Time hora_final) {
		this.hora_final = hora_final;
	}
}
