//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : OfertarDisciplinaPeriodoBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.negocio;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;


public class OfertarDisciplinaPeriodoBean {
	public void gravar(Disciplina disciplina) {
	
	}
	
	public void editar(Disciplina disciplina) {
	
	}
	
	public void excluir(Disciplina disciplina) {
	
	}
	
	public void consultaDisciplinas(String nome) {
	
	}
	
	public void visualizarDisciplinasPeriodo() {
	
	}
	
	public void consultaDiscOpt(String nome) {
	
	}
	
	public void consultaDiscObr(String nome) {
	
	}
}
