//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaVisualizarHorario.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.gui;


public class TelaVisualizarHorario {
	public void visualizarHorarioTurma(Object Turma turma) {
	
	}
	
	public void visualizarHorarioPeriodo() {
	
	}
	
	public void visualizarHorarioProfessor(Object HorariosProfessor professor) {
	
	}
}
