//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaDisponibilizarHorariosEDisciplinas.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.gui;


public class TelaDisponibilizarHorariosEDisciplinas {
	public void selecionarDisciplina() {
	
	}
	
	public void selecionarHorariosPreferenciais() {
	
	}
	
	public void gravar(Object Disciplina disciplinas, Object Horarios horarios) {
	
	}
}
