//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaOfertarDisciplinaPeriodo.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.gui;


public class TelaOfertarDisciplinaPeriodo {
	public void ofertarDisciplinas(Object Disciplina disciplina) {
	
	}
	
	public void inserirDiscipinaOptativa(Object Disciplina disciplina) {
	
	}
	
	public void inserirDisciplinaObrigatoria(Object Disciplina disciplina) {
	
	}
	
	public void selecionarPeriodo(Object Semestre semestre) {
	
	}
}
