//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaValidarHorarios.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.gui;


public class TelaValidarHorarios {
	public void visualizarHorarioProfessor(Object HorariosProfessor horario) {
	
	}
	
	public void validarHorarioProfessor(Object HorariosProfessor horario) {
	
	}
}
