//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : PersistenciaTurmaDAO.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.turma.dados;

import br.ufs.dsi.sistemaDeHorarios.horario.entidade.Horarios;
import br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma;


public class PersistenciaTurmaDAO {
	public void visualizarHistorico( Turma turma) {
	
	}
	
	public void gravarHorarioTurma(Horarios horarios) {
	
	}
	
	public void enviarDados( Turma turma) {
	
	}
}
