//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterDisciplinaBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.disciplina.negocio;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;

@ManagedBean
@RequestScoped
public class ManterDisciplinaBean {
	
	@ManagedProperty(value="#{disciplina}")
	private Disciplina disciplina;
	
		
	public String gravar() {
		return "sucesso";
	}
	
	public String excluir() {
		return "sucesso";
	}
	
	public String editar() {
		return "sucesso";
	}
	
	public String confirmar(){
		return "sucesso";
	}

	public String voltarPagina(){
		return "sucesso";
	}
	
	public Disciplina getDisciplina() {
		return disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}
	
	
}
