//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaFinalizarPeriodo.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.turma.gui;


public class TelaFinalizarPeriodo {
	public void finalizarPeriodo() {
	
	}
	
	public void enviarDados(Object Turma turma) {
	
	}
	
	public void editarDados(Object Turma turma) {
	
	}
}
