//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : PersistenciaTurmaDAO.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.turma.dados;

import br.ufs.dsi.sistemaDeHorarios.horario.entidade.Horarios;
import br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma;


public class PersistenciaTurmaDAO implements IPersistenciaTurma {
	/* (non-Javadoc)
	 * @see br.ufs.dsi.sistemaDeHorarios.turma.dados.IPersistenciaTurma#visualizarHistorico(br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma)
	 */
	@Override
	public void visualizarHistorico( Turma turma) {
	
	}
	
	/* (non-Javadoc)
	 * @see br.ufs.dsi.sistemaDeHorarios.turma.dados.IPersistenciaTurma#gravarHorarioTurma(br.ufs.dsi.sistemaDeHorarios.horario.entidade.Horarios)
	 */
	@Override
	public void gravarHorarioTurma(Horarios horarios) {
	
	}
	
	/* (non-Javadoc)
	 * @see br.ufs.dsi.sistemaDeHorarios.turma.dados.IPersistenciaTurma#enviarDados(br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma)
	 */
	@Override
	public void enviarDados( Turma turma) {
	
	}
}
