//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterDisciplinaBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.disciplina.negocio;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;

@ManagedBean
@SessionScoped
public class ManterDisciplinaBean {
	private Disciplina disciplina = new Disciplina();
	
		
	public void gravar(Disciplina disciplina) {
		this.disciplina = disciplina; 
	}
	
	public void excluir(Disciplina disciplina) {

	}
	
	public void editar(Disciplina disciplina) {

	}
	
	public String cadastraDisciplina(){
		return "sucesso";
	}

	public Disciplina getDisciplina() {
		return disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}
}
