//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ValidacaoDosProfessoresBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.negocio;


public class ValidacaoDosProfessoresBean {
	public void visualizarValidacao() {
	
	}
}
