//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : HorariosProfessor.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.entidade;


public class HorariosProfessor {
	private char tipo_horario;

	public char getTipo_horario() {
		return tipo_horario;
	}

	public void setTipo_horario(char tipo_horario) {
		this.tipo_horario = tipo_horario;
	}
}
