//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ProfessorSemestre.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.entidade;


public class ProfessorSemestre {
	private boolean validacao;

	public boolean isValidacao() {
		return validacao;
	}

	public void setValidacao(boolean validacao) {
		this.validacao = validacao;
	}
}
