//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : Disciplina.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.disciplina.entidade;


public class Disciplina {
	private String cod_disciplina;
	private String nome;
	private int carga_horaria;
	private char periodoDisciplina;
	private char tipo_disciplina;
	
	public String getCod_disciplina() {
		return cod_disciplina;
	}
	public void setCod_disciplina(String cod_disciplina) {
		this.cod_disciplina = cod_disciplina;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public int getCarga_horaria() {
		return carga_horaria;
	}
	public void setCarga_horaria(int carga_horaria) {
		this.carga_horaria = carga_horaria;
	}
	public char getPeriodoDisciplina() {
		return periodoDisciplina;
	}
	public void setPeriodoDisciplina(char periodoDisciplina) {
		this.periodoDisciplina = periodoDisciplina;
	}
	public char getTipo_disciplina() {
		return tipo_disciplina;
	}
	public void setTipo_disciplina(char tipo_disciplina) {
		this.tipo_disciplina = tipo_disciplina;
	}
}
