//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterProfessorBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.view;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;
import br.ufs.dsi.sistemaDeHorarios.professor.negocio.INegocioProfessor;
import br.ufs.dsi.sistemaDeHorarios.professor.negocio.NegocioProfessor;

@ManagedBean
@RequestScoped
public class ManterProfessorBean 
{
	@ManagedProperty(value="#{professor}")
	private Professor professor;
	INegocioProfessor professorNegocio;
	
	public ManterProfessorBean(){
		professorNegocio = new NegocioProfessor();
	}
	
	public void gravar() {				
		professorNegocio.gravar(professor);
	}
	
	public void excluir() {
		professorNegocio.excluir(professor);
	}
	
	public void editar() {
		professorNegocio.editar(professor);
	}
	
	
	public String confirmar(){
		return "sucesso";
	}
	
	public String voltarPagina(){
		return "sucesso";
	}
	
	/*(public String autenticar(){
		professor = professorNegocio.autenticar(professor);
		return "sucesso";
	}*/
	
	public Professor getProfessor() {
		return professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}
	

}
