//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterProfessorBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.view;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;
import br.ufs.dsi.sistemaDeHorarios.professor.negocio.INegocioProfessor;
import br.ufs.dsi.sistemaDeHorarios.professor.negocio.NegocioProfessor;

@ManagedBean
@RequestScoped
public class ManterProfessorBean 
{
	@ManagedProperty(value="#{professor}")
	private Professor professor;
	
	INegocioProfessor professorNegocio;
	private List<Professor> professores;
	
	private String login;
	private String senha;
	
	public ManterProfessorBean(){
		professorNegocio = new NegocioProfessor();
	}
	
	public List<Professor> getProfessores() {
		return visualizarProfessores();
	}	
	
	public List<Professor> visualizarProfessores(){
		
		professores = professorNegocio.visualizarProfessores();
				
		for (Professor professor : professores) {
			System.out.println(professor.getNome());
		  }
		
		return professores;		
	}
	
	public void gravar() {				
		professorNegocio.gravar(professor);
	}
	
	public void excluir() {
		professorNegocio.excluir(professor);
	}
	
	public void editar() {
		professorNegocio.editar(professor);
	}
	
	
	public String confirmar(){
		return "sucesso";
	}
	
	public String voltarPagina(){
		return "sucesso";
	}
	
	public String autenticar(){
		login = professor.getLogin().toString();
		senha = professor.getSenha().toString();
		String retorno = professorNegocio.autenticar(login, senha);
		return retorno;
	}
	
	public Professor getProfessor() {
		return professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}
	

}
