//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterProfessorBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.negocio;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;

@ManagedBean
@SessionScoped
public class ManterProfessorBean {
	private Professor professor = new Professor();
	
	
	public String gravar() {
		return "sucesso";
	}
	
	public String excluir() {
		return "sucesso";
	}
	
	public String editar() {
		return "sucesso";
	}
	
	public void visualizarDados() {
	
	}
	
	public String voltarPagina(){
		return "sucesso";
	}
	
	public void gravarDisciplinaProfessor(Disciplina disciplina) {
	
	}
	
	public void visualizarDisciplinaProfessor(Disciplina disciplina) {
	
	}

	public Professor getProfessor() {
		return professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}
}
