//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : FinalizarPeriodoBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.view;

import br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma;


public class FinalizarPeriodoBean {
	public void enviarDados(Turma turma) {
	
	}
	
	public void editarDados(Turma turma) {
	
	}
	
	public void finalizarPeriodo() {
	
	}
}
