//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ValidarHorariosBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.view;


public class ValidarHorariosBean {
	public void visualizarHorarioProfessor(int matricula) {
	
	}
	
	public void validarHorarioProfessor(int matricula) {
	
	}
	
	public void visualizarValidacoes() {
	
	}
}
