//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : VisualizarHorarioBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.view;

import br.ufs.dsi.sistemaDeHorarios.horario.entidade.HorariosProfessor;
import br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma;


public class VisualizarHorarioBean {
	public void visualizarHorarioTurma(Turma turma) {
	
	}
	
	public void visualizarHorarioPeriodo() {
	
	}
	
	public void visualizarHorarioProfessor(HorariosProfessor professor) {
	
	}
}
