//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaVisualizarHistorico.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.turma.gui;


public class TelaVisualizarHistorico {
	public void visualizarHistorico(Object Turma turma) {
	
	}
}
