//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : OrganizarHorarioBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.negocio;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.horario.entidade.HorariosProfessor;
import br.ufs.dsi.sistemaDeHorarios.horario.entidade.Semestre;
import br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma;


public class OrganizarHorarioBean {
	public void inserirDisciplinaOptativa(Disciplina disciplina) {
	
	}
	
	public void inserirDisciplinaObrigatoria(Disciplina disciplina) {
	
	}
	
	public void ofertaDisciplinas(Disciplina disciplina) {
	
	}
	
	public void selecionarDisciplinasEDias() {
	
	}
	
	public void visualizarPeriodo() {
	
	}
	
	public void visualizarHorarioPeriodo() {
	
	}
	
	public void visualizarDisciplinasPeriodo() {
	
	}
	
	public void visualizarDisciplinaProfessor(Disciplina disciplina) {
	
	}
	
	public void inserirHorarioProfessor(HorariosProfessor horarioProfessor) {
	
	}
	
	public void visualizarHorarioTurma(Turma turma) {
	
	}
	
	public void visualizarHorarioProfessor(HorariosProfessor horario) {
	
	}
	
	public void gravarDisciplina( Disciplina disciplina) {
	
	}
	
	public void selecionarPeriodo(Semestre semestre) {
	
	}
	
	public void montarHorario() {
	
	}
	
	public void editarHorariosPreferenciais() {
	
	}
	
	public void enviarHorarioProfessor() {
	
	}
	
	public void visualizarValidacoes() {
	
	}
}
