//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : PersistenciaValidacaoSemestreDAO.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.dados;


public class PersistenciaValidacaoSemestreDAO {
	public void gravarValidacao() {
	
	}
}
