//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : PersistenciaHorarioDAO.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.dados;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.horario.entidade.HorariosProfessor;


public class PersistenciaHorarioDAO {
	public void inserirDisciplinaObrigatoria(Disciplina disciplina) {
	
	}
	
	public void inserirDisciplinaOptativa(Disciplina disciplina) {
	
	}
	
	public void ofertarHorario() {
	
	}
	
	public void inserirHorarioProfessor(HorariosProfessor horarioProfessor) {
	
	}
	
	public void visualizarHorarioPeriodo(HorariosProfessor horarioProfessor) {
	
	}
	
	public void gravarHorario() {
	
	}
}
