//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : PersistenciaProfessorDAO.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.dados;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.horario.entidade.HorariosProfessor;
import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;


public class PersistenciaProfessorDAO {
	public void gravar(Professor professor) {
	
	}
	
	public void excluir(Professor professor) {
	
	}
	
	public void visualizarDados(Professor professor) {
	
	}
	
	public void gravarHorariosPreferenciais( HorariosProfessor horarios) {
	
	}
	
	public void gravarDisciplinasPreferenciais(Disciplina disciplina) {
	
	}
	
	public void gravarValidacao(HorariosProfessor horario) {
	
	}
}
