

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : Turma.java
//  @ Date : 16/05/2011
//  @ Author : 
//
//

package br.ufs.dsi.sistemaDeHorarios.turma.entidade;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;


public class Turma {
	private int id_turma;
	private int quantidade_aluno;
	private int total_aprovados;
	private int total_reprovados_falta;
	private int total_reprovados_media;
	private Disciplina disciplina = new Disciplina();
	private Professor professor = new Professor();
	
	public int getId_turma() {
		return id_turma;
	}
	public void setId_turma(int id_turma) {
		this.id_turma = id_turma;
	}
	public int getQuantidade_aluno() {
		return quantidade_aluno;
	}
	public void setQuantidade_aluno(int quantidade_aluno) {
		this.quantidade_aluno = quantidade_aluno;
	}
	public int getTotal_aprovados() {
		return total_aprovados;
	}
	public void setTotal_aprovados(int total_aprovados) {
		this.total_aprovados = total_aprovados;
	}
	public int getTotal_reprovados_falta() {
		return total_reprovados_falta;
	}
	public void setTotal_reprovados_falta(int total_reprovados_falta) {
		this.total_reprovados_falta = total_reprovados_falta;
	}
	public int getTotal_reprovados_media() {
		return total_reprovados_media;
	}
	public void setTotal_reprovados_media(int total_reprovados_media) {
		this.total_reprovados_media = total_reprovados_media;
	}
	public Disciplina getDisciplina() {
		return disciplina;
	}
	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}
	public Professor getProfessor() {
		return professor;
	}
	public void setProfessor(Professor professor) {
		this.professor = professor;
	}
}
