//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : EditarDadosProfessorBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.negocio;

import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;


public class EditarDadosProfessorBean {
	public void alterarDadosProfessor(Professor professor) {
	
	}
	
	public void visualizardadosProfessor(Professor professor) {
	
	}
}
