//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : DisponibilizarHorariosEDisciplinasBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.negocio;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.horario.entidade.HorariosProfessor;
import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;


public class DisponibilizarHorariosEDisciplinasBean {
	public void selecionarDisciplinas() {
	
	}
	
	public void selecionarHorariosPreferenciais(String nomeProfessor) {
	
	}
	
	public void gravarHorariosPreferenciais(HorariosProfessor horarios) {
	
	}
	
	public void gravarDisciplinasPreferenciais(Disciplina disciplinas) {
	
	}
	
	public void visualizarHorariosPreferenciais() {
	
	}
	
	public void editarHorariosPreferenciais(Professor professor) {
	
	}
}
