//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SISTEMA DE HORÁRIOS
//  @ File Name : TelaOrganizarHorarios.java
//  @ Date : 11/05/2011
//  @ Author : 
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.gui;


public class TelaOrganizarHorarios {
	public void visualizarDisciplinasPeriodo() {
	
	}
	
	public void inserirDisciplinaObrigatoria(Object Disciplina disciplina) {
	
	}
	
	public void inserirDisciplinaOptativa(Object Disciplina disciplina) {
	
	}
	
	public void visualizarDisciplinaProfessor(Object Disciplina disciplina) {
	
	}
	
	public void inserirHorarioProfessor(Object HorariosProfessor horarioProfessor) {
	
	}
	
	public void visualizarHorarioPeriodo() {
	
	}
	
	public void selecionarPeriodo(Object Semestre semestre) {
	
	}
	
	public void editarHorariosPreferenciais(Object Horarios horarios) {
	
	}
	
	public void montarHorario() {
	
	}
	
	public void enviarHorarioProfessor() {
	
	}
	
	public void visualizarValidacoes() {
	
	}
}
