//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : Disciplina.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.disciplina.entidade;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.NoneScoped;

@ManagedBean
@NoneScoped

public class Disciplina {
	private int cod_disciplina;
	private String nome;
	private int carga_horaria;
	private char periodo_disciplina;
	private char tipo_disciplina;
	
	public int getCod_disciplina() {
		return cod_disciplina;
	}
	public void setCod_disciplina(int cod_disciplina) {
		this.cod_disciplina = cod_disciplina;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public int getCarga_horaria() {
		return carga_horaria;
	}
	public void setCarga_horaria(int carga_horaria) {
		this.carga_horaria = carga_horaria;
	}
	
	public char getTipo_disciplina() {
		return tipo_disciplina;
	}
	public void setTipo_disciplina(char tipo_disciplina) {
		this.tipo_disciplina = tipo_disciplina;
	}
	public char getPeriodo_disciplina() {
		return periodo_disciplina;
	}
	public void setPeriodo_disciplina(char periodo_disciplina) {
		this.periodo_disciplina = periodo_disciplina;
	}
}
