//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterProfessorBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.negocio;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;
import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;


public class ManterProfessorBean {
	public void gravar(Professor professor) {
	
	}
	
	public void excluir(Professor professor) {
	
	}
	
	public void editar(Professor professor) {
	
	}
	
	public void visualizarDados( String nome) {
	
	}
	
	public void gravarDisciplinaProfessor(Disciplina disciplina) {
	
	}
	
	public void visualizarDisciplinaProfessor(Disciplina disciplina) {
	
	}
}
