//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : PersistenciaDisciplinaDAO.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.disciplina.dados;


import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;


public class PersistenciaDisciplinaDAO implements IPersistenciaDisciplina {
	/* (non-Javadoc)
	 * @see br.ufs.dsi.sistemaDeHorarios.disciplina.dados.IPersistenciaDisciplina#gravar(br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina)
	 */
	@Override
	public void gravar(Disciplina disciplina) {
		
	}
	
	/* (non-Javadoc)
	 * @see br.ufs.dsi.sistemaDeHorarios.disciplina.dados.IPersistenciaDisciplina#editar(br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina)
	 */
	@Override
	public void editar(Disciplina disciplina) {
	
	}
	
	/* (non-Javadoc)
	 * @see br.ufs.dsi.sistemaDeHorarios.disciplina.dados.IPersistenciaDisciplina#excluir(br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina)
	 */
	@Override
	public void excluir(Disciplina disciplina) {
	}
	
	@Override
	public Disciplina visualizarDisciplina(Disciplina disciplina) {
		return disciplina;		
	}

}
