//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : ManterDisciplinaBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.disciplina.negocio;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;


public class ManterDisciplinaBean {
	public void gravar(Disciplina disciplina) {
	
	}
	
	public void excluir(Disciplina disciplina) {
	
	}
	
	public void editar(Disciplina disciplina) {
	
	}
}
