//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : Professor.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.professor.entidade;

import java.util.Collection;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import br.ufs.dsi.sistemaDeHorarios.disciplina.entidade.Disciplina;

@ManagedBean
@SessionScoped

@Entity
@Table(name="tb_professor")
public class Professor {
	@Id
	@Column(name="MATRICULA")
	private int matricula;
	@Column(name="NOME")
	private String nome;
	@Column(name="TELEFONE")
	private String telefone;
	@Column(name="EMAIL")
	private String email;
	@Column(name="AREA")
	private String area;
	@Column(name="LOGIN")
	private String login;
	@Column(name="SENHA")
	private String senha;
	@Column(name="CORDENADOR")
	private char cordenador;
	
	@ManyToMany 
	@JoinTable(name="tb_disciplina_professor",
				joinColumns=@JoinColumn(name="MATRICULA"),
				inverseJoinColumns=@JoinColumn(name="COD_DISCIPLINA")	)
	private Collection<Disciplina> disciplinas;
	
	public int getMatricula() {
		return matricula;
	}
	public void setMatricula(int matricula) {
		this.matricula = matricula;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getTelefone() {
		return telefone;
	}
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getArea() {
		return area;
	}
	public void setArea(String area) {
		this.area = area;
	}
	public String getLogin() {
		return login;
	}
	public void setLogin(String login) {
		this.login = login;
	}
	public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}
	
	
	public Collection<Disciplina> getDisciplinas() {
		return disciplinas;
	}
	public void setDisciplinas(Collection<Disciplina> disciplinas) {
		this.disciplinas = disciplinas;
	}
	public char getCordenador() {
		return cordenador;
	}
	public void setCordenador(char cordenador) {
		this.cordenador = cordenador;
	}
	
	
}
