//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : DisponibilizarHorariosEDisciplinasBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.horario.view;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import br.ufs.dsi.sistemaDeHorarios.professor.entidade.Professor;

@ManagedBean
@SessionScoped
public class DisponibilizarHorariosEDisciplinasBean 
{
	private boolean seg1;
	private boolean seg2;
	private boolean seg3;
	private boolean ter1;
	private boolean ter2;
	private boolean ter3;
	private boolean qua1;
	private boolean qua2;
	private boolean qua3;
	private boolean qui1;
	private boolean qui2;
	private boolean qui3;
	private boolean sex1;
	private boolean sex2;
	private boolean sex3;
	
	public boolean isSeg1() {
		return seg1;
	}
	public void setSeg1(boolean seg1) {
		this.seg1 = seg1;
	}
	public boolean isSeg2() {
		return seg2;
	}
	public void setSeg2(boolean seg2) {
		this.seg2 = seg2;
	}
	public boolean isSeg3() {
		return seg3;
	}
	public void setSeg3(boolean seg3) {
		this.seg3 = seg3;
	}
	public boolean isTer1() {
		return ter1;
	}
	public void setTer1(boolean ter1) {
		this.ter1 = ter1;
	}
	public boolean isTer2() {
		return ter2;
	}
	public void setTer2(boolean ter2) {
		this.ter2 = ter2;
	}
	public boolean isTer3() {
		return ter3;
	}
	public void setTer3(boolean ter3) {
		this.ter3 = ter3;
	}
	public boolean isQua1() {
		return qua1;
	}
	public void setQua1(boolean qua1) {
		this.qua1 = qua1;
	}
	public boolean isQua2() {
		return qua2;
	}
	public void setQua2(boolean qua2) {
		this.qua2 = qua2;
	}
	public boolean isQua3() {
		return qua3;
	}
	public void setQua3(boolean qua3) {
		this.qua3 = qua3;
	}
	public boolean isQui1() {
		return qui1;
	}
	public void setQui1(boolean qui1) {
		this.qui1 = qui1;
	}
	public boolean isQui2() {
		return qui2;
	}
	public void setQui2(boolean qui2) {
		this.qui2 = qui2;
	}
	public boolean isQui3() {
		return qui3;
	}
	public void setQui3(boolean qui3) {
		this.qui3 = qui3;
	}
	public boolean isSex1() {
		return sex1;
	}
	public void setSex1(boolean sex1) {
		this.sex1 = sex1;
	}
	public boolean isSex2() {
		return sex2;
	}
	public void setSex2(boolean sex2) {
		this.sex2 = sex2;
	}
	public boolean isSex3() {
		return sex3;
	}
	public void setSex3(boolean sex3) {
		this.sex3 = sex3;
	}
	public String selecionarDisciplinas() 
	{
		return "sucesso";
	}
	public String voltarPagina() 
	{
		return "sucesso";
	
	}
	
	public void selecionarHorariosPreferenciais(String nomeProfessor) {
	
	}
	
	public String gravarHorariosPreferenciais()
	{
		return "sucesso";
	}
	
	public String gravarDisciplinasPreferenciais()
	{
		return "sucesso";
	}
	
	public void visualizarHorariosPreferenciais()
	{
			
	
	}
	
	public void editarHorariosPreferenciais(Professor professor) {
	
	}
}
