//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :  SISTEMA DE HORÁRIOS
//  @ File Name : VisualizarHistoricoBean.java
//  @ Date : 13/05/2011
//  @ Author : @
//
//



package br.ufs.dsi.sistemaDeHorarios.turma.negocio;

import br.ufs.dsi.sistemaDeHorarios.turma.entidade.Turma;


public class VisualizarHistoricoBean {
	public void visualizarHistorico(Turma turma) {
	
	}
}
